### PR TITLE
implemented forward from webdriver spec

### PR DESCRIPTION
**Pull request by lazypassion**

### CODE REVIEW

**Comment by lazypassion** [comment]
lol whoops. That wasn't what I was planning.

**Comment by saresend** [comment]
No problem haha :)

**Comment by lazypassion** [comment]
Do I need the chrome driver as well as the selenium webdriver? I'm confused about setting up the selenium webdriver server.

**Comment by saresend** [comment]
Can you describe your process a bit more? What exactly are you running to run the tests? I apologize if the docs don't do a very good job describing exactly how to get the tests to run!

**Comment by lazypassion** [comment]
Ah sorry, I'm at the root of the folder for the project then i run `cargo test --test element_tests`.

**Comment by saresend** [comment]
And the error message, is it just that it seems to fail to connect to the server?

**Comment by lazypassion** [comment]
Yeah, I'll look into it. It just seems to be a weird problem with windows and permissions i believe. I'll try it on ubuntu and hopefully it should work.

**Comment by saresend** [comment]
Ah gotcha, I believe I've run it on both linux and MacOS, but haven't tested on windows. Feel free to file an issue!

**Comment by lazypassion** [comment]
How exactly do you test this library? Because I'm on ubuntu 18.04. I downloaded the latest selenium jar file. I ran that file so it's listening on port 4444 and then i run cargo test from the root of the crate, however all the tests fail. So I'm wondering what I'm doing wrong.

**Comment by lazypassion** [comment]
I added a test that uses forward and back and it seems to work fine. Let me know if you want to improve the test or separate it into two tests.

**Comment by saresend** [comment]
Sweet, it all looks great! Thanks for your PR 😃

**Pull request merged**
